name: RankShop
main: Angga7Togk\RankShop\Main
version: 2.1
api: 5.0.0
author: Angga7Togk
description: "RankShop"

commands:
  rankshop:
    description: "Open RankShop"
    permission: rankshop.cmd

permissions:
  rankshop.cmd:
    description: "rankshop Permission"
    default: true
